# Generated by Django 4.0.1 on 2023-02-14 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=26, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('profilePhoto', models.ImageField(default='/default.png', upload_to='')),
                ('rank', models.CharField(default='Novice', max_length=26)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TypingTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField()),
                ('wpm', models.IntegerField()),
                ('accuracy', models.IntegerField()),
                ('raw', models.IntegerField()),
                ('dateTaken', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='typemonk.userprofile')),
            ],
        ),
    ]
